require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '11.0'
install! 'cocoapods', :deterministic_uuids => false

use_modular_headers!

target 'Glimpse' do
  config = use_native_modules!

  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :flags => flags,
    :fabric_enabled => flags[:fabric_enabled],
    :hermes_enabled => flags[:hermes_enabled],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(installer)
  end
end
